### ISSUE TITLE
Niet voor elke pagina een section nodig

### ISSUE THREAD

**Issue by hiddebraun-ma** [Joeyvdkuijl/BAP-Trello#1]
https://github.com/Joeyvdkuijl/BAP-Trello/blob/62ba07a1416c89a228766ee098a7b6a9aac6d86c/resources/views/layouts/layout.blade.php#L14-L27

Je kan gewoon 1 section maken met de naam 'content'.
In je views overschrijf je dan de inhoud voor die section. Snap je?
De inhoud van de pagina's komt dan op de plke waar in je layout de 'content' section staat.

**Comment by Joeyvdkuijl** [comment]
ja dat kan ook

**Comment by Joeyvdkuijl** [comment]
ik heb het gedaan
